# ----
# Site

title: Antigua Grecia
url: "https://gonzalo123.github.io/grecia"
baseurl:
google_analytics_key:
show_full_navigation: false

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Mis apuntes sobre la Antigua Grecia.
author:
  name: Gonzalo Ayuso
  email: gonzalo123@gmail.com
  twitter: gonzalo123
social:
  name: gonzalo123
  links:
    - https://twitter.com/gonzalo123

# -----
# Build

timezone: Europe/Madrid

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000


types:
  - minor
  - major
